spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/Spectra
    username: postgres
    password: bnm11091
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
  liquibase:
    change-log: classpath:db/changelog/changelog.xml
    enabled: true
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
app:
  in-memory-model:
    enabled: false
